### ISSUE TITLE
Make `Filter`s public

### ISSUE THREAD

**Issue by nicholasspencer** [SwiftGen/StencilSwiftKit#120]
Is there a particular reason the filters are scoped `internal`? It would be nice if they were `public` to use the filters directly in other customs filters.

**Comment by nicholasspencer** [comment]
I have a fork that scopes the filters publicly but i'm wondering if it would be useful to move the filters into their own target which could be used by `StencilSwiftKit` and other gen tools.

I know that I should be using macros for most of this stuff but there are certain situations where using both macros and custom filters would be nice.

**Comment by djbe** [comment]
No particular reason TBH, beyond the fact we didn't think about it 😆 
This is a perfect starter task, if you want to make a PR. 

Note: you can get started on it now if you really want, but might be best to wait until #127 is merged (which modernises lots of things).
