### ISSUE TITLE
Test Swift 4.2 (or drop support for it)

### ISSUE THREAD

**Issue by djbe** [SwiftGen/StencilSwiftKit#128]
As discussed in #127, we need to decide what to do with Swift 4.2.

Do we expect lots of people to still use Swift 4.2? Any platform that supports Swift 4.2 also supports Swift 5, so we may as well drop it?

**Comment by djbe** [comment]
Anyone got strong opinions on this one? Otherwise we might as wel drop it.

The main project, besides SwiftGen, that uses SSK is Sourcery, and they're on Swift 5.

**Comment by fortmarek** [comment]
It seems there are no strong opinions on this one - I think it'd be fine to drop it. If you want to, I can create a PR for this - and afterwards it'd make sense to create the 2.8.0 release?

**Comment by djbe** [comment]
Yes definitely 👍 

I'm hoping to merge #130 as well for 2.8.0, but it isn't a blocker. We can always merge that one afterwards.

**Comment by schemers** [comment]
Is there a timeline on a 2.8.0 release? Using `.branch("stable")` seems to be causing some heartburn to SPM that I wasn't encountering when using version number. 🙇
