### ISSUE TITLE
Ensure tests work again

### ISSUE THREAD

**Issue by djbe** [SwiftGen/StencilSwiftKit#2]

**Comment by AliSoftware** [comment]
Will we need a submodule pointing to SwiftGen/templates here?

Maybe not, as all the tests will do in this repo is test Stencil nodes and filters so those tests can be even more fine-grained and use some JSON as input fixtures to test each node.

OTOH testing on actual data like strings, even though it would more be liked integration tests than unit tests, could be interesting as well…

**Comment by djbe** [comment]
No, the templates submodule is used in SwiftGenKit (for fixtures0 and SwiftGen itself (for templates and fixtures).

**Comment by AliSoftware** [comment]
Yeah makes sense that tests for StencilSwiftKit we shouldn't rely on templates and resource fixtures anyway, as this repo is supposed to be used by things other than SwiftGen anyway (Sourcery in particular) and some nodes and filters might even move to Stencil proper in the future so tests need to be independent 👍

**Comment by djbe** [comment]
Jup. Concerning more granular tests, we could add some basic tests for:
- `call`/`macro` nodes
- `set` node
using bare-bones templates. I'd also split up the strings tests over multiple files, and maybe move the common input strings into 1 constants file.

**Comment by AliSoftware** [comment]
Yeah, seems fair. Especially now that we'll have dedicated repos, it's the best time to make more organised tests, more separated and split in multiple files if needed.
