### ISSUE TITLE
Any way of declaring an array or looping a single value?

### ISSUE THREAD

**Issue by samskiter** [SwiftGen/StencilSwiftKit#44]
I've posted a question here about looping a single value:

https://github.com/kylef/Stencil/issues/113

I wonder if there is anything that StencilSwiftKit has declared that allows this?

**Comment by djbe** [comment]
You could just check if `myValue.count` is true, or greater than 0. Should that expression evaluate to `nil`, it will be considered as false --> a single value. Otherwise you have an array.

**Comment by samskiter** [comment]
@djbe Its proving kind of nasty to use that way. I'm actually doing it by using the `empty` clause of for loops

**Comment by djbe** [comment]
TBH, I think in this case that the generated context just has a bizarre structure. It shouldn't return either a `Annotation` in some cases, and `Array<Annotation>` in others. The context generator should always return a `Array<Annotation>`, even if there's just one object.

I don't see this as being a common enough use case to add a specific filter/tag for.

**Comment by samskiter** [comment]
sounds reasonable, thanks for the reply @djbe 

Another related tag that might be useful would be the 'split' function - splitting a string up into an array would mean I could use just one Annotation and split the content up into its parts the template

**Comment by djbe** [comment]
Hmmm, that might be an interesting use case, if you want, you can open an issue to discuss the definition of such a filter. And it might be a good starter task, if you'd like to implement it 😉

**Comment by AliSoftware** [comment]
I'm indeed surprised that Stencil itself have `join` but doesn't have `split` 🤔  Interesting filter to add indeed
