### ISSUE TITLE
Pool swift reserved words en masse into a single list. 

### ISSUE THREAD

**Issue by johndpope** [SwiftGen/StencilSwiftKit#49]
it would be useful to have a list of swift reserved words that that could be separately maintained. 

I came across this just today 
https://github.com/apple/swift-protobuf/tree/master/Reference

kind of fits the bill. 
https://github.com/apple/swift-protobuf/blob/master/Reference/generated_swift_names_fields.pb.swift

Having trouble using the java / c++ code generation tool with antlr. 
being able to plug in a list would pay dividends down the track. 
related.
https://github.com/antlr/antlr4/issues/1851

**Comment by djbe** [comment]
Hi @johndpope,

The ideal source for such a list would be the Swift team / repository itself. Right now, we got our list from the Swift documentation.

Even if there would be such a maintained list, we'd still need to include it somehow into the StencilSwiftKit code without breaking SPM for example, where all code needs to reside in `Sources` and each sub folder is a module... (last I checked)

**Comment by johndpope** [comment]
fyi - this is what Apple protobuf team use.  https://github.com/apple/swift-protobuf/blob/master/Sources/PluginLibrary/SwiftLanguage.swift#L118-L166
