### ISSUE TITLE
Allow to use strings filters on CustomStringConvertable

### ISSUE THREAD

**Issue by Antondomashnev** [SwiftGen/StencilSwiftKit#64]
This was proposed in #58. The idea is that at the moment all strings filters from `Filters+Strings...` expect `String` parameter and throw exception if it's not satisfied, however we could change this rule to accept all parameters that can be described as a string, which `CustomStringConvertable` is made for 😄 

We'll also make use of it in [Sourcery](https://github.com/krzysztofzablocki/Sourcery)

**Comment by djbe** [comment]
Should be pretty easy to replace all casts to `String` with casts to `StringConvertible`, then add calls to `String(describing:)`.

It could be interesting to refactor this out into it's own function, that way we can easily write tests for it and assure it works everywhere in exactly the same way. If at some point we want to add support for another type conversion to string, we can do it in that function.

**Comment by djbe** [comment]
Note: add it to https://github.com/SwiftGen/StencilSwiftKit/blob/master/Sources/Filters.swift, maybe as a `parseString` function.

**Comment by AliSoftware** [comment]
I believe we already have a helper function called something similar to parseBoolParam or something for booleans, we should follow the same naming convention for strings and start grouping them in some helper namespace maybe?
