### ISSUE TITLE
For range loop or alternative

### ISSUE THREAD

**Issue by royalstream** [SwiftGen/StencilSwiftKit#74]
I've done my due diligence but I can't seem to find a way to do this:

{% for i in range(1,5) %}
... do something with i ...
{% endfor %}

I apologize beforehand if there's an obvious way to do it but I can't seem to find it.
The closest thing I've been to a solution is using an array that has at least the number of elements I want, doing a map to get the counter and then filter the counters outside the range (which is way too ugly)

I also tried to create an array variable using {% set %} to no use.
And I also tried "1,2,3,4"|split but there's no such filter.

Am I missing something obvious?

**Comment by AliSoftware** [comment]
I don't think you're missing anything obvious, as the `{% for %}` tag are usually used to iterate over an existing array provided by the Stencil context already, and I don't think we have a tag to dynamically create an array or sequence from 0 to N from a template.

I'm surprised that `"1,2,3,4"|split(',')` doesn't work though.

Might be a good idea for a new tag or a `for i in 0...5` kind of variation

\cc @kylef @ilyapuchka thoughts?

**Comment by ilyapuchka** [comment]
I was actually thinking about implementing range literals over last days, but dropped this idea, I can imaging some complications in parsing this as variables also can use `.`. Maybe something like
`for i in 1 to 3` can be an alternative?

**Comment by ilyapuchka** [comment]
Regarding split filter, I can't see it not in Stencil, nor here, but definitely can be a quick fix for this case.

**Comment by ilyapuchka** [comment]
@royalstream And of course you can just have range passed in as variable in context, Stencil supports iterating open and closed ranges.

**Comment by AliSoftware** [comment]
Wow indeed I'm quite surprised we don't have this one, for some reason I was pretty sure we had it already… (I probably thought that because we do have its counterpart `join` 😉)
Would definitely be a nice addition in any case 👍

**Comment by royalstream** [comment]
Using `"1,2,3"|split(',')` would be an inferior alternative anyway because you wouldn't be able to do things like this:

```
{% for i in 1 to 10 %}
  {% for j in 1 to i %}
....
  {% endfor %}
{% endfor %}
```

**Comment by ilyapuchka** [comment]
FYI I created a PR that implements this https://github.com/kylef/Stencil/pull/179

**Comment by ilyapuchka** [comment]
I've also submitted PR to Stencil with `split` filter https://github.com/kylef/Stencil/pull/187

**Comment by djbe** [comment]
Note: we should update to Stencil 0.11 to get the new `split` filter and range support.
