### ISSUE TITLE
Calling macro with a parameter invoking a filter crashes

### ISSUE THREAD

**Issue by gushromp** [SwiftGen/StencilSwiftKit#76]
So I have a macro
`{% macro someMacro someParameter %}`

And when I attempt to invoke it like this:
`{% call someMacro myType.storedVariables|annotated:"someAnnotation" %}`

I get this fatal exception:

`Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<SourceryRuntime.Struct 0x7f94a2e1a5a0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key storedVariables|annotated:"json".'`

Calling the macro without the filter on storedVariables works just fine:
`{% call someMacro myType.storedVariables %}`

**Comment by Liquidsoul** [comment]
Hi @gushromp,

[`macro`](https://github.com/SwiftGen/StencilSwiftKit/blob/master/Documentation/tag-macro.md) and [`call`](https://github.com/SwiftGen/StencilSwiftKit/blob/master/Documentation/tag-call.md) are [StencilSwiftKit](https://github.com/SwiftGen/StencilSwiftKit) tags and I do not think that they support filters on passed arguments. `call` evaluates them as plain text.

Depending on what your `macro` does, maybe you could use the `map` [tag](https://github.com/SwiftGen/StencilSwiftKit/blob/master/Documentation/tag-map.md) to work around this?

**Comment by Liquidsoul** [comment]
Hi @gushromp,

Depending on what your `macro` does, maybe you could use the `map` [tag](https://github.com/SwiftGen/StencilSwiftKit/blob/master/Documentation/tag-map.md) to work around this issue?

**Comment by gushromp** [comment]
Hi @Liquidsoul 
Thanks for the help, but unfortunately that doesn't seem to work, either, for my use case - since it seems that the `map` tag does not keep the original type of what it's mapping over.

So for example, if I write:
`{% map myType.storedVariables into myArray %}{{ item }}{% endmap %}`

Originally, the type of `item` is a Sourcery `Variable` type, but after being mapped it gets transformed into some other type and some functions no longer work, such as `isArray`. 

Perhaps I'm just doing the mapping wrong? I tried using just `item` instead of `{{ item }}` but it gets parsed as a string literal.

**Comment by djbe** [comment]
You can always use the `set` tag inside before your `call` tag, or inside your `macro` block to apply filters I think.

I'm curious though, how does Stencil do this? (ping @kylef) Is it this line?
```swift
VariableNode(variable: resolvable).render(context)
```
https://github.com/kylef/Stencil/blob/master/Sources/FilterTag.swift#L31

**Comment by ilyapuchka** [comment]
@djbe wrapping in variable node will stringify the result but current tests expect the type of arguments to be preserved. So just compiling arguments as filter expressions should be sufficient.
