### ISSUE TITLE
 `set` tag not respecting scope in `for` loop

### ISSUE THREAD

**Issue by DanielAsher** [SwiftGen/StencilSwiftKit#82]
I'm trying to create a variable that is updated within the scope of a `for` tag, but have been unsuccessful:
In the following example, `lastCaseName` is never mutated, always taking the value `initial`.
Is this possible with [Stencil](github.com/kylef/Stencil) or perhaps `swifttemplate`?
```
{% for root in types.implementing.BeRoot %}
    {% set lastCaseName %}initial{% endset %}
    class func reduce(_ state: State, with event: Event) -> State {
        switch(state.mode, event) {
        {% for case in root.cases %}
            case (.{{ lastCaseName }}, .did{{ lastCaseName|upperFirstLetter  }}):
            return state.with { $0.mode = {{ case.name }} }
            {% set lastCaseName %}{{ case.name }}{% endset %}
        {% endfor %}
        return state        
    }
}
{% endfor %}

**Comment by djbe** [comment]
Yeah no, variables in stencil are scoped within for tags (amongst others, we also have macro blocks in StencilSwiftKit). That means that whatever changes you make during a for loop, won't be accessible outside of that for loop.

What you can always do is add an `if` test *inside* the `for` loop and check what the value of `forloop.last`.

**Comment by DanielAsher** [comment]
@djbe thanks for the quick response!

`{% forloop.last %}` seems to be a `Boolean` valued indicator of the whether this is the last execution of the for loop. I think I need access to the last **value** of the for loop variable so I can have the current and last values at the same time. How would you generate the following?
```
// source file
enum ABC {
   case a,b,c
}
// generated file
func reduce(first: ABC, second: ABC) {
   switch (first, second) {
   case (.a, .b): print("ab")
   case (.b, .c): print("bc")
   default: print("unhandled")
   }
}
```

**Comment by DanielAsher** [comment]
@djbe I thought ` {% set lastCaseName %}{{ case.name }}{% endset %}``` would update the value of the `lastCaseName` within the scope of the enclosing `for` loop. But it **does not**. This seems a bug to me...

**Comment by djbe** [comment]
No, each iteration of the for loop is a new scope.

I now understand what you're trying to achieve. I don't think there's an easy built-in way to achieve this, unfortunately. But, if you don't mind some bizarre code (untested):

```
{% for case1 in items %}
    {% if not forloop.first %}
        {% set firstLoopIndex %}forloop.counter{% endset %}
        {% for case2 in items %}
            {% if forloop.counter0 == firstLoopIndex %}
                // do stuff
                // {{ case1 }}, {{ case2 }}
            {% endif %}
        {% endfor %}
    {% endif %}
{% endfor %}
```

**Comment by DanielAsher** [comment]
`{% set firstLoopIndex %}forloop.counter{% endset %}` produces bad output.
Did you mean `{% set firstLoopIndex %}{{ forloop.counter }}{% endset %}
Also Is `forloop.counter0` a syntax error?

**Comment by djbe** [comment]
Yeah I forgot the {{}} tags 😅. The counter0 is meant to be there, it’s a 0-based index instead of 2-based (see stencil docs)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DanielAsher** [comment]
@djbe thanks again for you response! Very much appreciated 👍 
For anyone else encountering this scenario, beware: Sourcery versions < 11 do not support `forloop.counter0`. Luckily for me, Sourcery v11 was released 7 hours ago 😉

I would also suggest that special mention should be made in the docs that a for loop introduces a new scope with each iteration. This is highly irregular, and break the notion of what a scope is. This is surely a `Stencil` shortcoming, and needs to be explicitly called out.

**Comment by AliSoftware** [comment]
Hi @DanielAsher 

I'd suggest you open an issue in the Stencil repo directly about that missing documentation about for loops creating new scopes on each iteration. You'd have better chances that the author of Stencil would see it and process it :wink:
