### ISSUE TITLE
reusable macro templates

### ISSUE THREAD

**Issue by nferruzzi** [SwiftGen/StencilSwiftKit#91]
I've a lot of similar templates with a lot of common macros, I'd like to just have a copy of each single macro stored inside a common file included by all templates. Unfortunately it looks like I can't just {% include .. %} a macro template and use the macros defined there. When I do call them they are not defined. Is it possible to export macros in a way that could be used from the "outer" context ? thanks in advance

**Comment by nferruzzi** [comment]
I actually wrote the solution myself; maybe this can be useful for someone else ..
This is a simple import node, the rendered output is discarded as well so the macro file can have space and comments between macros blocks 💃 

I use it at the top of my template files 
```
{% import "Macros.swift" %}
```

```
import Foundation

class ImportNode : NodeType {
    let templateName: Variable

    class func parse(_ parser: TokenParser, token: Token) throws -> NodeType {
        let bits = token.components()

        guard bits.count == 2 else {
            throw TemplateSyntaxError("'import' tag requires one argument, the template file to be imported.")
        }

        return ImportNode(templateName: Variable(bits[1]))
    }

    init(templateName: Variable) {
        self.templateName = templateName
    }

    func render(_ context: Context) throws -> String {
        guard let templateName = try self.templateName.resolve(context) as? String else {
            throw TemplateSyntaxError("'\(self.templateName)' could not be resolved as a string")
        }

        let template = try context.environment.loadTemplate(name: templateName)

        _ = try template.render(context)
        return ""
    }
}

```

**Comment by ilyapuchka** [comment]
@nferruzzi this will be a nice thing to have, but I couldn't find any PR for that.

**Comment by nferruzzi** [comment]
cool I'll prepare one in the next days

**Comment by cornr** [comment]
Hi @nferruzzi this is exactly what I am looking for.
When is "in the next days"? 😝
It would be really cool to see this in Sourcery.
