### ISSUE TITLE
Release 2.6.0

### ISSUE THREAD

**Issue by djbe** [SwiftGen/StencilSwiftKit#97]
I'm not sure if I consider this a breaking change:
> Migrated to PathKit for url filters. The dirname will return '.' for a filename without base directory.

I think it's more of a bug fix TBH (we're bringing the output in line with PathKit).

Depending on our choice, the version'll be 2.6.0 or 3.0.0.

**Comment by yonaskolb** [comment]
Personally I’d also consider this a fix (2.6.0)

**Comment by AliSoftware** [comment]
Yeah, I see it as a bug fix too :+1:
